create table if not exists gatepasses (
  id bigint generated by default as identity primary key,
  visitor_name text not null,
  mobile text not null,
  purpose text not null,
  person_to_meet text not null,
  status text not null default 'Pending',
  created_at timestamptz not null default now()
);

insert into gatepasses
(visitor_name, mobile, purpose, person_to_meet, status)
values
('Demo Visitor', '9876543210', 'Meeting', 'Admin', 'Pending');
